Maximus905/voiceDbApp

protected/Controllers/Export.php
=> Add autofilter to excel

protected/Controllers/Export.php
=> Fix autofilter for excel

protected/Controllers/Export.php
=> Change format for export ip

protected/Controllers/Dataports.php
=> Fix dataport controller

protected/Components/DataSetProcessor.php, protected/Models/Appliance.php, protected/Models/ModuleItem.php
Change to input the lastUpdate
=> Change to input the lastUpdate

protected/Models/DataPort.php
Change the output format of mac address
=> Change the output format of mac address

protected/Controllers/Dataports.php, protected/Controllers/Modal.php, protected/Templates/Modal/EditAppliance.html
Добавил сортировку по portname для вывода dataports
=> Добавил сортировку по portname для вывода dataports

protected/Components/DataSetProcessor.php, protected/Controllers/Test.php, protected/Layouts/resources/js/script.js, protected/Models/Appliance.php, protected/Templates/Admin/Devices.html
=> Fix last update

protected/Components/DataSetProcessor.php, protected/Controllers/Dataports.php, protected/Controllers/RServer.php
=> Change output format logs

protected/Components/DataSetProcessor.php
=> Minor fixes for the dataport controller

protected/Components/DSPappliance.php, protected/Components/DSPprefixes.php, protected/Controllers/Export.php
Add to fill a color for an appliance in an excel
=> Add to fill a color for an appliance in an excel

protected/Components/DSPappliance.php
=> Fix dspappliance

protected/Commands/Rclient.php, protected/Components/DSPappliance.php, protected/Controllers/RServer.php, protected/Exceptions/LocationException.php
=> fix dspappliance again

protected/Components/DSPappliance.php
=> fix dspappliances again2

protected/Components/DSPappliance.php, protected/Models/Appliance.php
Add the method Delete() to the Appliance
=> Add the method Delete() to the Appliance

protected/Components/AxlClient.php, protected/Components/RisPortClient.php
Fix axlClient and risPortClient
=> Fix axlClient and risClient

protected/Controllers/Export.php
=> Fix EXCEL export

protected/Components/DSPappliance.php
Delete processing inUse for appliances
=> Delete processing inUse for appliances

protected/Controllers/Export.php
=> Добавил vg в exportIp

protected/Commands/CucmClient.php
=> fix CucmClient

protected/Controllers/Export.php
Сделал экспорт телефонов в excel
=> Dev cucm export

protected/Commands/CucmsPhones.php, protected/Models/Appliance.php, protected/Models/Phone.php
=> Release test model

protected/Commands/CucmsPhones.php, protected/Models/Appliance.php, protected/Models/Phone.php
=> Fix a saving phones

protected/Commands/CucmsPhones.php, protected/Models/Phone.php
=> fix save phones

protected/Models/Phone.php
Изменил привязку телефонов к офисам
=> Изменил привязку телефонов к офисам

protected/Migrations/m_1505298858_alterPhoneInfoTable.php, protected/Models/Phone.php, protected/Models/PhoneInfo.php
Add the field unknownLocation to PhoneInfo
=> Add the field unknownLocation to PhoneInfo

protected/Controllers/Export.php
Добавил обработку офисов в excel
=> Release phones

protected/Controllers/Export.php
Добавил подсветку для appliance max age в excel
=> Добавил подсветку для appliance max age в excel

protected/Controllers/Export.php
Добавил поле PublisherDescription в Excel
=> Release fix appliaces

protected/Components/DSPappliance.php, protected/Components/DSPcluster.php
=> Release add new cucms

protected/Commands/CucmsPhones.php, protected/Components/DSPphones.php, protected/Models/Appliance.php, protected/Models/Phone.php
remade cucmsPhones and small fixes
=> remade cucmsPhones

protected/Commands/CucmsPhones.php, protected/Components/DSPappliance.php, protected/Components/DSPphones.php, protected/Components/DSPprefixes.php, protected/Models/DataPort.php
Исправил сохранение details в DataPorts
=> Исправил сохранение details в DataPorts

protected/Controllers/Logs.php, protected/Layouts/Index.html, protected/Templates/Logs/Phones.html
=> Add the phones logs

protected/Commands/CucmsPhones.php
=> Добавил опрос соседей по snmp

protected/Commands/CucmsPhones.php, protected/Controllers/Logs.php, protected/Templates/Logs/Phones.html
Добавил в лог вывод номера телефона
=> Добавил в лог вывод номера телефона

protected/Commands/CucmsPhones.php, protected/Controllers/Logs.php, protected/Templates/Logs/Phones.html
Добавил город, адрес, офис в логи по телефонам
=> Добавил город, адрес, офис в логи по телефонам

protected/Controllers/Logs.php
=> small fixes

protected/Components/DSPappliance.php
поправил создание moduleItem при создании appliance
=> поправил создание moduleItem при создании appliance

build/production/build.xml, build/production/config.php, protected/Commands/CucmsPhones.php, protected/Components/DSPappliance.php, protected/Components/DSPprefixes.php, protected/Models/Platform.php, protected/Models/PlatformItem.php, protected/Models/Software.php
Fix dspappliance and add getNeighborsBySsh
=> Fix dspappliance and add getNeighborsBySsh

protected/Components/DSPphones.php, protected/config.php
=> fix dspphones

protected/Components/DSPappliance.php
Change the platformTitle on the chassis in the dspAppliances
=> Change the platformTitle on the chassis in the dspAppliances

protected/Components/DSPappliance.php, protected/Components/DSPphones.php
Added processing of the value of the chassis
=> Added processing of the value of the chassis

protected/Components/DSPphones.php
=> redesing the dspappliances

protected/Components/DSPappliance.php
=> fix dspApplince

protected/Components/DSPappliance.php, protected/Components/DSPphones.php
Сделал обработку имен телефонов
=> Сделал обработку имен телефонов

protected/Commands/CucmsPhones.php
cdp - исключил некоторые модели
=> cdp - исключил некоторые модели

protected/Commands/CucmsPhones.php
=>  fix for the cdp neighbors

protected/Controllers/Export.php
=> Release add storage1c

protected/Controllers/Export.php
=> remade Export

protected/Storage1CModels/InventoryItem1C.php
fix dateOfRegistration's validation
=> fix dateOfRegistration's validation

build/production/build.xml, build/production/config.php, protected/Controllers/Export.php, protected/Models/PhoneLastCall.php, protected/config.php
=>  add last call

build/production/config.php
=> fix config

protected/Components/DSPphones.php
=> fixed dspPhones

protected/Models/PhoneLastCall.php
=> changed phoneLastCall's table

protected/Controllers/Export.php
=> fixed PhoneLastCall

protected/Components/ContentFilter.php, protected/Components/Reports/ApplianceTypeWithoutInventoryReport.php, protected/Controllers/Report.php, protected/Models/ApplianceType.php, protected/Templates/Report/New.html, protected/ViewModels/DevModulePortGeo.php
add report for the appliances without inventory number
=> add report for the appliances without inventory number

protected/Migrations/m_1529589714_changeInventoryItem1cView.php, protected/Migrations/m_1529590162_changeDevAppliance1cView.php, protected/Migrations/m_1529590887_changeDevModule1cView.php, protected/ViewModels/Dev_Appliance1C.php, protected/ViewModels/Dev_Module1C.php, protected/ViewModels/InventoryItem1C.php
=> changed all views_1c

protected/Controllers/Export.php, protected/Controllers/Logs.php, protected/Layouts/Index.html, protected/Templates/Logs/Phones.html
add export button for the phones errors logs
=> add export button for the phones errors logs

protected/Components/DSPphones.php
change to save a serial number for phone 7936 and 7937
=> change to save a serial number for phone 7936 and 7937

protected/Migrations/m_1537962578_createViewFor1CDevelopers.php
=> create view for 1C developers

protected/Migrations/m_1538044355_createForeing1CTable.php
=> create foreing_1c table

protected/Migrations/m_1538049410_alterPhoneInfoTable.php, protected/Models/Appliance.php
change a type of the phoneInfo fields
=> change a type of the phoneInfo fields

protected/Commands/CucmsPhones.php, protected/Components/DSPphones.php
changed to process phone location
=> changed to process phone location

protected/Controllers/Export.php
=> add fields to the excel

protected/Components/DSPphones.php
change cdp processing for phones
=> change cdp processing for phones

protected/Components/DSPphones.php
delete cdp processing for phones from web interface
=> delete cdp processing for phones from web interface

protected/Commands/CucmsPhones.php, protected/Components/Connection/Connection.php, protected/Components/Connection/ConnectionImpl/SshConnectionHandler.php, protected/Components/Import/Neighbors.php, protected/Components/Import/NeighborsImpl/PhonesCdpNeighborsFromSwitchesBySsh.php
add cumcsPhones/updateCdpNeighborsFromSwitchesBySsh
=>  add cumcsPhones/updateCdpNeighborsFromSwitchesBySsh

protected/Components/Connection/ConnectionImpl/SshConnectionHandler.php
fix warning of sshConnectionHandler
=> fix warning of sshConnectionHandler

protected/Commands/CucmsPhones.php, protected/Components/Connection/ConnectionImpl/SshConnectionHandler.php, protected/Components/Import/NeighborsImpl/PhonesCdpNeighborsFromSwitchesBySsh.php
fix error output for cdp_neighbors
=> fix error output for cdp_neighbors

protected/Controllers/Export.php
=> add ipExport by ip

protected/Migrations/m_1542807537_alterNomenclature1CTable.php, protected/Storage1CModels/Nomenclature1C.php
=> change Nomenclature1C

protected/Migrations/m_1542871803_changeInventoryItem1cView.php
=> change inventoryItem1c view

protected/Controllers/Admin.php, protected/Controllers/Device.php, protected/Migrations/m_1543320408_changePlatformItemTable.php, protected/Migrations/m_1543324829_changePlatformsTable.php, protected/Models/Platform.php, protected/Models/PlatformItem.php, protected/Templates/Admin/Devparts.html, protected/Templates/Device/DevicesTableBody.html, protected/Templates/Modal/AddPlatform.html, protected/Templates/Modal/EditAppliance.html, protected/Templates/Modal/EditPlatform.html
=>  add SerialNumberAlt

protected/Controllers/Device.php, protected/Migrations/m_1543405598_changeDevModulePortGeoView.php, protected/Templates/Device/DevicesTableBody.html, protected/Templates/Device/DevicesTableHeader.html, protected/Templates/Device/Info.html, protected/Templates/Modal/EditAppliance.html, protected/ViewModels/DevModulePortGeo.php
=>  add platform Details

protected/Controllers/Modal.php, protected/Templates/Device/DevicesTableBody.html, protected/Templates/Modal/EditAppliance.html
=> fix U on deviceInfo

protected/Components/Export/ApplianceToExcel.php, protected/Migrations/m_1543490886_changeDevPhoneInfoGeoView.php
=> add U to excel export

protected/Migrations/m_1543561685_changeDevModulePortGeoView.php, protected/Templates/Device/Info.html, protected/ViewModels/DevModulePortGeo.php
=>  add U filtering

protected/Migrations/m_1543575769_changeDevModulePortGeoView.php, protected/Templates/Device/DevicesTableBody.html, protected/Templates/Device/DevicesTableHeader.html, protected/Templates/Device/Info.html, protected/ViewModels/DevModulePortGeo.php
=> add inventory user

protected/Controllers/UsersPhone.php, protected/Layouts/Index.html, protected/Migrations/m_1543823226_changeMapLotusDB.php, protected/Migrations/m_1543826947_createLotusDbPhoneBookMatView.php, protected/Migrations/m_1543924211_createReportPhoneByLotusUserView.php, protected/Templates/UsersPhone/Default.html, protected/Templates/UsersPhone/UsersPhoneTableBody.html, protected/Templates/UsersPhone/UsersPhoneTableBody_old.html, protected/Templates/UsersPhone/UsersPhoneTableHeader.html, protected/ViewModels/UsersPhoneView.php
=>  add users phone view

protected/Components/Export/ApplianceToExcel.php, protected/Migrations/m_1544184643_changeReportPhoneByLotusUserView.php
=> change appliance Excel

protected/Components/Export/ApplianceToExcel.php, protected/Migrations/m_1544688132_changeDevPhoneInfoGeoView.php, protected/ViewModels/DevPhoneInfoGeo.php
=> add altSerialNumber to Excel

Configs/devGeoPivotStatisticByAgentsPhonesWithBodyFooter.php, Configs/devGeoPivotStatisticByAgentsPhonesWithBodyFooterBF.php, protected/Components/Tables/PivotTable.php, protected/Controllers/Report.php, protected/Controllers/TableConfigs.php, protected/Layouts/Index.html, protected/Migrations/m_1545392649_createForeignHdsTable.php, protected/Migrations/m_1545733186_createHdsStatsByYesterdayPhones.php, protected/Models/Phone.php, protected/Templates/Report/AgentsPhonesStatsReport.html, protected/Templates/Report/AgentsPhonesStatsReportByModelsBody.html, protected/Templates/Report/AgentsPhonesStatsReportByModelsBodyFooter.html, protected/Templates/Report/AgentsPhonesStatsReportByModelsHeader.html, protected/ViewModels/DevModulePortGeo.php, protected/ViewModels/HdsAgentsPhonesStatView.php
=> add agents statistic

protected/Migrations/m_1546068901_changeHdsStatsByYesterdayPhonesView.php
=> fix agents stats view

protected/Migrations/m_1546085839_changeHdsStatsByYesterdayPhonesView.php
=> fix agents dublicates

protected/Migrations/m_1548671305_moveForeignHdsTableToHdsDailyAgentsDnStatisticsTable.php, protected/Migrations/m_1548671575_createHdsWeeklyAgentsDnStatisticsTable.php, protected/Migrations/m_1548671857_createUpdateHdsWeeklyStatsFunctions.php
=> add hds weekly stats

protected/Controllers/HdsStats.php, protected/Templates/HdsStats/WeeklyStatsByOfficesOnPrefix558.html, protected/Templates/HdsStats/WeeklyStatsByOfficesOnPrefix559.html, protected/Templates/HdsStats/WeeklyStatsByPrefixes.html
add hds weekly stats controller
=> add hds weekly stats controller

protected/Components/DSPappliance.php, protected/Components/DSPprefixes.php, protected/Migrations/m_1549975593_changeApplianceTable.php, protected/Models/Appliance.php
=> change table Appliance

protected/Migrations/m_1550052526_changeUpdateHdsWeeklyStatsFunctions.php
=> fix hds stats

protected/Controllers/Report.php, protected/ViewModels/DevCallsStats.php
=> fix dev calls stats

protected/Controllers/Export.php
=> add export nexus ip

protected/Components/DSPprefixes.php, protected/Controllers/RServer.php, protected/Models/Appliance.php, protected/Models/DPortType.php, protected/Models/Vrf.php
=> fixed dsp prefixes

protected/Components/DSPprefixes.php, protected/Models/DataPort.php
=> change dspPrefixes

protected/Models/Appliance.php
=> change Appliamce

protected/Components/WorkAppliance.php, protected/Components/WorkCluster.php, protected/Components/WorkPrefixes.php
=> fix to throw errors

protected/Components/WorkAppliance.php
=> fix workAppliance

protected/Commands/CucmsPhones.php, protected/Components/Log/ApplianceLog.php, protected/Components/Log/DisplayedLog.php, protected/Components/Log/EraseableLog.php, protected/Components/Log/LevelLog.php, protected/Components/Log/Log.php, protected/Components/Log/PhoneLog.php, protected/Controllers/Export.php, protected/Controllers/Log.php, protected/Layouts/Index.html, protected/Templates/Log/Appliance.html, protected/Templates/Log/Phone.html
change to output logs for appliances
=> change to output logs for appliances

protected/Layouts/Index.html, protected/Templates/BasePhone/Default.html, protected/Templates/Device/Info.html, protected/Templates/Log/Appliance.html, protected/Templates/UsersPhone/Default.html
change the Button on DropDown on the bar
=> change the Button on DropDown on the bar

protected/Components/WorkAppliance.php, protected/Components/WorkCluster.php, protected/Components/WorkPrefixes.php, protected/Controllers/RServer.php
=> fix dspProcessors

protected/Controllers/Ip.php, protected/Templates/Ip/Default.html
=> add ip controller

protected/Commands/UpdateHostsByAddresses.php
=> fix error log

protected/Commands/UpdateHostsByAddresses.php
change updateHostsByAddresses command
=> change updateHostsByAddresses command

protected/Commands/CucmsPhones.php, protected/Commands/UpdateHostsByAddresses.php, protected/Components/DSPerror.php, protected/Components/InventoryAppliance.php, protected/Components/InventoryCluster.php, protected/Components/Prefixes.php, protected/Components/StreamLogger.php, protected/Controllers/Export.php, protected/Controllers/RServer.php
=> Changed export ipAppliances

protected/Commands/CucmsPhones.php
=>  fix cucmsPhones

protected/Components/InventoryAppliance.php, protected/Controllers/Phone.php
fixed to find phone in phone's controller
=> fixed to find phone in phone's controller

protected/Controllers/Api.php, protected/Layouts/Json.html, protected/Migrations/m_1567682416_changeMapLotusDB.php, protected/Migrations/m_1567683189_createLotusDbPhoneBookExtendsMatView.php, protected/Templates/Api/Employee.html, protected/ViewModels/ApiView_Employee.php
=> add lotus employee api

protected/Controllers/Api.php, protected/Models/Appliance.php, protected/Templates/Api/Location.html
=> add location api

protected/Controllers/Api.php
=> change employee api

protected/Components/InventoryAppliance.php
=> fix InventoryAppliance

protected/Controllers/Api.php, protected/Templates/Api/Networks.html
=> add networks api

protected/Controllers/Api.php, protected/Models/Network.php
=> fix networks api

build/configTemplate/config.php, protected/Controllers/MappingTables.php, protected/Migrations/m_1570707239_mapPcDB.php, protected/Migrations/m_1570773601_createPcDataMatViews.php, protected/Migrations/m_1571052498_createMappedPcDataView.php, protected/Templates/MappingTables/PcData.html, protected/ViewModels/MappedPcData.php
=> add pc data view

protected/Migrations/m_1570707239_mapPcDB.php
=> fix pcData view

protected/Migrations/m_1571052498_createMappedPcDataView.php, protected/Templates/MappingTables/PcData.html
=> fix pc data view

protected/Migrations/m_1572416112_changeMapPcDb.php
=> change pc data migration

protected/Controllers/MappingTables.php, protected/Migrations/m_1572428493_changeMappedPcDataView.php, protected/Templates/MappingTables/PcData.html, protected/ViewModels/MappedPcData.php
=> change pc data

protected/Migrations/m_1573539637_changeReportPhoneByLotusUserView.php
change ReportPhoneByLotusUserView
=> change ReportPhoneByLotusUserView

protected/Migrations/m_1573555901_fixReportPhoneByLotusUserView.php, protected/Templates/UsersPhone/UsersPhoneTableBody.html
fix ReportPhoneByLotusUserView
=> fix ReportPhoneByLotusUserView

protected/Components/Cucm.php, protected/Components/CucmAxl.php, protected/Migrations/m_1579163804_updateMapPcDb.php, protected/Templates/MappingTables/PcData.html, protected/ViewModels/MappedPcData.php
=> Update pc data

protected/Commands/CucmsPhones.php, protected/Components/Cucm.php, protected/Components/Cucm/Models/RedirectedPhone.php, protected/Components/CucmAxl.php, protected/Components/StreamLogger.php, protected/Controllers/Export.php, protected/Controllers/RedirectedPhones.php, protected/Layouts/Index.html, protected/Layouts/IndexAgGrid.html, protected/Migrations/m_1579504736_createRedirectedPhonesTable.php, protected/Templates/RedirectedPhones/Default.html, protected/Templates/RedirectedPhones/FromCucm.html, protected/Templates/RedirectedPhones/RedirectedPhoneTableBody.html, protected/Templates/RedirectedPhones/RedirectedPhoneTableHeader.html
add redirected phone from cucm
=> Add redirected phone from cucm

protected/Controllers/RedirectedPhones.php, protected/Templates/RedirectedPhones/FromCucm.html
=> fix redirected phones

protected/Controllers/RedirectedPhones.php
=> change redirected phones

protected/Components/Cucm.php, protected/Components/Cucm/Models/RedirectedPhone.php, protected/Components/CucmAxl.php, protected/Controllers/Export.php, protected/Controllers/RedirectedPhones.php, protected/Templates/RedirectedPhones/FromCucm.html
=> add the report names to the cucms for redirected phones

protected/Migrations/m_1580812509_changeMapPcDb.php
=> change map pcDb

protected/Migrations/m_1585293724_changeMapPcDb.php
change map pcDb - add field pc_term
=> change map pcDb - add field pc_term

protected/Templates/MappingTables/PcData.html, protected/ViewModels/MappedPcData.php
=> change view pdData

protected/Components/Export/ApplianceToExcel.php, protected/Controllers/Phone.php
add Prefix action to Phone controller and fix the excel export
=> add Prefix action to Phone controller and fix the excel export

protected/Components/Cucm/UnRegisteredPhonesService.php, protected/Components/Ssh/SshClient.php, protected/Components/Swiitch/CiscoSwitch.php, protected/Components/Swiitch/SwitchService.php, protected/Controllers/Phone.php, protected/Models/Appliance.php
=> add unregistered phones

protected/Components/Cucm/UnRegisteredPhonesService.php, protected/Components/Swiitch/CiscoSwitch.php
change unregisteredPhones service
=> change unregisteredPhones service

protected/Controllers/Phone.php, protected/Templates/Phone/UnregisteredConnectedToSwitch.html, protected/Templates/Phone/UnregisteredInOffice.html
fix unregisteredPhones service
=> fix unregisteredPhones service

protected/Commands/CucmsPhones.php, protected/Components/Cucm/UnRegisteredPhonesService.php, protected/Components/DateTimeService.php, protected/Components/StreamLogger.php, protected/Components/Swiitch/CiscoSwitch.php, protected/Components/Swiitch/SwitchService.php, protected/Controllers/Phone.php, protected/Models/Appliance.php
fix error of unregisteredPhones service
=> fix error of unregisteredPhones service

protected/Components/Phones/PhoneService.php
fix update unregisteredPhones service
=> fix update unregisteredPhones service

protected/Components/Cucm/Cucm.php, protected/Components/DSPphones.php, protected/Components/Phones/Cisco/CiscoPhone8945.php, protected/Components/Swiitch/SwitchService.php
=> fix CUCM service

build/buildAnt.xml, build/configTemplate/config.php, protected/Components/Export/ApplianceToExcel.php, protected/Controllers/Phone.php, protected/Migrations/m_1602832577_createMapVerint558Db.php, protected/Migrations/m_1602847260_createPhoneRecorderView.php, protected/Templates/Phone/Recordable.html, protected/ViewModels/PhoneRecorder_View.php
=> add PhoneRecorder_View model
